### ISSUE TITLE
Grass blocks from other mods turn into vanilla dirt

### ISSUE THREAD

**Issue by cadaverous-eris** [delvr/Repose#15]
It seems as though this only happens to grass blocks which were automatically added to the config file.
An example of a block that is affected by this would be any grass block from Biomes o' Plenty, like loamy grass, for instance.

This is using version 1.5.2 of the mod on MC 1.12.2 with Forge 14.23.1.2600

**Comment by delvr** [comment]
Hi the-releast-stu, thanks for reporting this. Starting with the new latest 1.5.3 release, non-vanilla grass-type blocks should remain themselves when falling. Ideally they would turn into their own version of dirt, but since I cannot know how each mod makes that association, this should be the next best solution. Please give it a try and re-open this issue if this behavior still occurs. Thanks!
