### ISSUE TITLE
Disable Falling Block Breaking

### ISSUE THREAD

**Issue by shade28** [delvr/Repose#19]
I used your mod in my pack and I absolutely love it.
https://minecraft.curseforge.com/projects/skytouched

I disabled the hill climbing features and just use the gravity though. I added trees to the list and its super fun. Kinda wish that we had more structure tests so branches dont fall off so easily. 

The issue im having though is falling entities breaking when dropping onto non solid blocks. Players make tree farms with half slabs to break the wood and such.  I would really love it if falling entities treated non solid blocks like half slabs and torches as solid blocks and just burred things. Is this a possibility? even as a toggle in the config file.

**Comment by delvr** [comment]
Hi shade28, glad to hear you're enjoying the mod! Yours is an interesting use case - basically all hanging branches eventually fall down? 

Now in terms of block breakage, if a block falls on a solid block like a half-slab, the falling block should break as you intend; but if it falls on a non-solid block like a torch, the non-solid block will break instead. This is the "normal" behavior, however if the server is lagging or if nearby chunks are unloaded, blocks will fall instantly i.e. instead teleport downwards and replace any non-solid block they land on. Perhaps this is the behavior you are seeing?

In any case it would make sense to have the instant-fall behavior to mimic the normal behavior more closely so I'll make a note of that for the next version.

**Comment by shade28** [comment]
Ideally I would like an option to disable falling blocks breaking at all. so if it landed on a halfslab it would just sorta hover over the slab. I realize the technical side of things are a bit complicated. but It would be nice.

**Comment by delvr** [comment]
Just released Repose 1.6 which brings instantly-falling blocks' behavior in line with their "normal" behavior; this might address some of your earlier points.

As for customizing the breaking behavior, it seems that you could achieve this simply by choosing what blocks to land on. So if you want the falling blocks to break you'd put half-slabs, otherwise just normal blocks. Does this make sense?

**Comment by shade28** [comment]
I know thats how it works, and its been working like that just fine. i
didnt have a problem with the instantly falling blocks. it was a nice way
to save on lag stuff. what I had an issue with was when i put blocks (like
logs) on the gravity table, players would make treefarms that break the
trees with halfslabs. and I just wanted to disable breaking of any blocks
when they landed. Its not a big deal. but I wanted to at least clarify what
i was asking for.

**Comment by delvr** [comment]
Aaaah, I understand now. I got your initial suggestion backwards because I thought you were asking on behalf of your players trying to make "tree farms" and not always succeeding, but it seems you were rather trying to clamp down on such behavior as an exploit. :-) 

Although I wouldn't want a block resting in mid-air on a half-slab as default behavior, I can certainly look at making this configurable as an option. One challenge with Repose is that the configs aren't currently synchronized (#14) so it can be difficult for the server to enforce behavior on a client, but I'll look into it.

**Comment by PDelta41** [comment]
I would like to second this request.  In my survival game, I have Immersive Engineering pipes buried in a railyard.  Some of these pipes are only below one layer of dirt or gravel.  I would like to be able to have granular blocks sit on top of these pipes without breaking. Obviously, this doesn't model a direct bury, where fill would occupy the space around the pipe, but I feel it's a close enough approximation, and probably a lot easier to code.

**Comment by delvr** [comment]
I added a config option in Repose 1.6.4 to enable this, with the current falling/breaking behavior as the default. As usual, since there's no auto-sync make sure the client config matches the server's.
