### ISSUE TITLE
Investigate possibility of players becoming randomly frozen

### ISSUE THREAD

**Issue by Sunconure11** [delvr/Repose#28]
Sorry if this ends up being the wrong mod, but I'm trying to nuke an issue I've noted I keep having where my character flat out refuses to move, and using /kill does not help. I was only told to go here to investigate the possibility of an oddity on this end involving movement.

**Comment by delvr** [comment]
Hi Sunconure11, this might be because your config settings for "sloping blocks", "granular blocks" and/or "natural stone blocks" are different between your server and your client(s); could you check this in the config GUI or the `config/repose.properties` file, and let me know if making those identical fixes it? (I'll be trying to automate the client/server config synchronization in the future as per https://github.com/delvr/Repose/issues/14.)

**Comment by Sunconure11** [comment]
This is happening on a singleplayer world, I'll try regenerating the file.

**Comment by Sunconure11** [comment]
Regenerating the file did nothing. I have found some possible culprits in some parts of the issue, however.

https://github.com/SoraZodia/Cannibalism/issues/13

**Comment by delvr** [comment]
Looks like the issue is resolved on the other mod's end.
