### ISSUE TITLE
Crash with slime kind of mobs

### ISSUE THREAD

**Issue by Foreck1** [delvr/Repose#37]
Game crashes, it seems, when other mods' slime mobs interact with repose's slopes. at least according to VanillaFix

Defiled slime from DefiledLands
https://paste.dimdev.org/mugajuyahe.mccrash
Blue slime form Tconstruct
https://paste.dimdev.org/ogagurulaf.mccrash

**Comment by delvr** [comment]
Hi Foreck1,
I wasn't able to reproduce the crash after spawning both types of slimes on Repose-sloping blocks (and collapsing a bunch around them for good measure). The crash might be due to an interaction with other mods. Do you remember what was happening with the slimes prior to the crash, or would you be able to trigger it again and record the event? Thanks!

**Comment by Foreck1** [comment]
Sorry for not answering. As I never tested this again and you couldn't replicate it, I guess there's no point on leaving this open.
